// schema.config.js
// Полная схема базы данных bergauto для PostgreSQL
// Включает структуру таблиц + все необходимые индексы

export const SchemaConfig = {
  Bosses: [
    { Name: "ID", Type: "INTEGER", PK: true },
    { Name: "Name", Type: "VARCHAR(100)", NotNull: true },
    { Name: "BossName", Type: "VARCHAR(50)" },
    { Name: "Mem", Type: "TEXT" },
    { Name: "Tel", Type: "VARCHAR(50)" },
    { Name: "Address", Type: "VARCHAR(100)" },
    { Name: "INN", Type: "VARCHAR(50)" },
    { Name: "OGRN", Type: "VARCHAR(50)" },
    { Name: "KPP", Type: "VARCHAR(50)" },
    { Name: "RS", Type: "VARCHAR(50)" },
    { Name: "KS", Type: "VARCHAR(50)" },
    { Name: "BIK", Type: "VARCHAR(50)" },
    { Name: "Bank", Type: "VARCHAR(100)" },
    { Name: "RS2", Type: "VARCHAR(50)" },
    { Name: "KS2", Type: "VARCHAR(50)" },
    { Name: "BIK2", Type: "VARCHAR(50)" },
    { Name: "Bank2", Type: "VARCHAR(100)" },
    { Name: "BuhName", Type: "VARCHAR(50)" },
    { Name: "NextInvoiceNomer", Type: "INTEGER" },
    { Name: "NDS", Type: "DOUBLE PRECISION" },
    { Name: "BaseCode", Type: "SMALLINT" },
    { Name: "ID_Ref", Type: "INTEGER" },
    { Name: "ToExport", Type: "BOOLEAN", Default: "false" },
  ],

  Cargos: [
    { Name: "ID", Type: "INTEGER", PK: true },
    { Name: "Name", Type: "VARCHAR(100)", NotNull: true },
    { Name: "IsFood", Type: "BOOLEAN", Default: "false" },
    { Name: "IsRef", Type: "BOOLEAN", Default: "false" },
    { Name: "IsFull", Type: "BOOLEAN", Default: "false" },
    { Name: "Mem", Type: "TEXT" },
    { Name: "BaseCode", Type: "SMALLINT" },
    { Name: "ID_Ref", Type: "INTEGER" },
    { Name: "ToExport", Type: "BOOLEAN", Default: "false" },
  ],

  Customers: [
    { Name: "ID", Type: "INTEGER", PK: true },
    { Name: "NameShort", Type: "VARCHAR(100)", NotNull: true },
    { Name: "ID_Cargo", Type: "INTEGER" },
    { Name: "ManIn", Type: "VARCHAR(100)" },
    { Name: "ManOut", Type: "VARCHAR(100)" },
    { Name: "IsCash", Type: "BOOLEAN", Default: "false" },
    { Name: "Mem", Type: "TEXT" },
    { Name: "ID_Tariff", Type: "INTEGER", NotNull: true },
    { Name: "Tel", Type: "VARCHAR(50)" },
    { Name: "Address", Type: "VARCHAR(100)" },
    { Name: "INN", Type: "VARCHAR(50)" },
    { Name: "OGRN", Type: "VARCHAR(50)" },
    { Name: "KPP", Type: "VARCHAR(50)" },
    { Name: "RS", Type: "VARCHAR(50)" },
    { Name: "KS", Type: "VARCHAR(50)" },
    { Name: "BIK", Type: "VARCHAR(50)" },
    { Name: "Bank", Type: "VARCHAR(100)" },
    { Name: "BaseCode", Type: "SMALLINT" },
    { Name: "ID_Ref", Type: "INTEGER" },
    { Name: "ToExport", Type: "BOOLEAN", Default: "false" },
  ],

  Tariffs: [
    { Name: "ID", Type: "INTEGER", PK: true },
    { Name: "Name", Type: "VARCHAR(50)", NotNull: true },
    { Name: "Wei0", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "Wei1", Type: "DOUBLE PRECISION" },
    { Name: "Wei2", Type: "DOUBLE PRECISION" },
    { Name: "Wei3", Type: "DOUBLE PRECISION" },
    { Name: "Wei4", Type: "DOUBLE PRECISION" },
    { Name: "Wei5", Type: "DOUBLE PRECISION" },
    { Name: "WeiPrice0", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "WeiPrice1", Type: "DOUBLE PRECISION" },
    { Name: "WeiPrice2", Type: "DOUBLE PRECISION" },
    { Name: "WeiPrice3", Type: "DOUBLE PRECISION" },
    { Name: "WeiPrice4", Type: "DOUBLE PRECISION" },
    { Name: "WeiPrice5", Type: "DOUBLE PRECISION" },
    { Name: "Vol0", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "Vol1", Type: "DOUBLE PRECISION" },
    { Name: "Vol2", Type: "DOUBLE PRECISION" },
    { Name: "Vol3", Type: "DOUBLE PRECISION" },
    { Name: "Vol4", Type: "DOUBLE PRECISION" },
    { Name: "Vol5", Type: "DOUBLE PRECISION" },
    { Name: "VolPrice0", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "VolPrice1", Type: "DOUBLE PRECISION" },
    { Name: "VolPrice2", Type: "DOUBLE PRECISION" },
    { Name: "VolPrice3", Type: "DOUBLE PRECISION" },
    { Name: "VolPrice4", Type: "DOUBLE PRECISION" },
    { Name: "VolPrice5", Type: "DOUBLE PRECISION" },
    { Name: "MinPrice", Type: "DOUBLE PRECISION" },
    { Name: "MinPrice2", Type: "DOUBLE PRECISION" },
    { Name: "FreeInOutWei", Type: "DOUBLE PRECISION" },
    { Name: "FreeInOutVol", Type: "DOUBLE PRECISION" },
    { Name: "PriceHourKat1", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "PriceHourKat2", Type: "DOUBLE PRECISION" },
    { Name: "PriceHourKat3", Type: "DOUBLE PRECISION" },
    { Name: "PriceHourKat4", Type: "DOUBLE PRECISION" },
    { Name: "PriceHourKat5", Type: "DOUBLE PRECISION" },
    { Name: "PriceHourSleep", Type: "DOUBLE PRECISION" },
    { Name: "PriceRefReic", Type: "DOUBLE PRECISION" },
    { Name: "Mem", Type: "TEXT" },
    { Name: "AddHour", Type: "DOUBLE PRECISION" },
    { Name: "BaseCode", Type: "SMALLINT" },
    { Name: "ID_Ref", Type: "INTEGER" },
    { Name: "ToExport", Type: "BOOLEAN", Default: "false" },
  ],

  xSaldo: [
    { Name: "ID_CustomerPay", Type: "INTEGER", NotNull: true },
    { Name: "ID_Boss", Type: "INTEGER", NotNull: true },
    { Name: "IsCash", Type: "BOOLEAN", NotNull: true, Default: "false" },
    { Name: "Count", Type: "INTEGER", NotNull: true },
    { Name: "Cost", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "Pays", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "IsNomer", Type: "BOOLEAN", NotNull: true, Default: "false" },
    { Name: "BuildID", Type: "INTEGER" },
  ],

  Applications: [
    { Name: "ID", Type: "INTEGER", PK: true },
    { Name: "DateReg", Type: "TIMESTAMP", NotNull: true, Default: "NOW()" },
    { Name: "TimeInStart", Type: "INTEGER" },
    { Name: "IsFixedIn", Type: "BOOLEAN", Default: "false" },
    { Name: "TimeOutStart", Type: "INTEGER" },
    { Name: "IsFixedOut", Type: "BOOLEAN", Default: "false" },
    { Name: "ID_Customer", Type: "INTEGER", NotNull: true },
    { Name: "ID_CustomerOut", Type: "INTEGER", NotNull: true },
    { Name: "ID_PointIn", Type: "INTEGER", NotNull: true },
    { Name: "ID_PointOut", Type: "INTEGER", NotNull: true },
    { Name: "IsSelfIn", Type: "BOOLEAN", Default: "false" },
    { Name: "IsSelfOut", Type: "BOOLEAN", Default: "false" },
    { Name: "ID_Cargo", Type: "INTEGER", NotNull: true },
    { Name: "Weight", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "Volume", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "CountPcs", Type: "DOUBLE PRECISION" },
    { Name: "IsCash", Type: "BOOLEAN", Default: "false" },
    { Name: "Mem", Type: "TEXT" },
    { Name: "Sum", Type: "DOUBLE PRECISION" },
    { Name: "TimeIn", Type: "INTEGER" },
    { Name: "TimeOut", Type: "INTEGER" },
    { Name: "ManIn", Type: "VARCHAR(100)" },
    { Name: "ManOut", Type: "VARCHAR(100)" },
    { Name: "StartInPlan", Type: "TIMESTAMP" },
    { Name: "EndInPlan", Type: "TIMESTAMP" },
    { Name: "StartOutPlan", Type: "TIMESTAMP" },
    { Name: "EndOutPlan", Type: "TIMESTAMP" },
    { Name: "ID_Task", Type: "INTEGER" },
    { Name: "IsInsure", Type: "BOOLEAN", Default: "false" },
    { Name: "Total", Type: "DOUBLE PRECISION" },
    { Name: "IsGuard", Type: "BOOLEAN", Default: "false" },
    { Name: "DateWorkIn", Type: "TIMESTAMP", NotNull: true, Default: "(NOW() + INTERVAL '1 day')" },
    { Name: "DateWorkOut", Type: "TIMESTAMP" },
    { Name: "ID_Tariff", Type: "INTEGER", NotNull: true },
    { Name: "SumInsure", Type: "DOUBLE PRECISION" },
    { Name: "SumGuard", Type: "DOUBLE PRECISION" },
    { Name: "Stage", Type: "INTEGER" },
    { Name: "ID_CustomerPay", Type: "INTEGER", NotNull: true },
    { Name: "IsCashIN", Type: "BOOLEAN", Default: "false" },
    { Name: "IsCashOUT", Type: "BOOLEAN", Default: "false" },
    { Name: "ID_XInvoice", Type: "INTEGER" },
    { Name: "SumUser", Type: "DOUBLE PRECISION" },
    { Name: "SumUserText", Type: "TEXT" },
    { Name: "IsWantInvoice", Type: "BOOLEAN", Default: "false" },
    { Name: "Nomer", Type: "INTEGER" },
    { Name: "BaseCode", Type: "SMALLINT" },
    { Name: "ID_Ref", Type: "INTEGER" },
    { Name: "ToExport", Type: "BOOLEAN", Default: "false" },
  ],

  XInvoices: [
    { Name: "ID", Type: "INTEGER", PK: true },
    { Name: "ID_Application", Type: "INTEGER", NotNull: true },
    { Name: "Nomer", Type: "INTEGER" },
    { Name: "Date", Type: "TIMESTAMP", NotNull: true },
    { Name: "Cost", Type: "DOUBLE PRECISION" },
    { Name: "IsFixed", Type: "BOOLEAN", NotNull: true, Default: "false" },
    { Name: "Pays", Type: "DOUBLE PRECISION" },
    { Name: "Name", Type: "TEXT", NotNull: true },
    { Name: "Mem", Type: "TEXT" },
    { Name: "ID_Boss", Type: "INTEGER", NotNull: true },
    { Name: "IsUseSecondAccount", Type: "BOOLEAN", NotNull: true, Default: "false" },
    { Name: "BaseCode", Type: "SMALLINT" },
    { Name: "ID_Ref", Type: "INTEGER" },
    { Name: "ToExport", Type: "BOOLEAN", NotNull: true, Default: "false" },
  ],

  XInvoicePays: [
    { Name: "ID", Type: "INTEGER", PK: true },
    { Name: "ID_XInvoice", Type: "INTEGER", NotNull: true },
    { Name: "Date", Type: "TIMESTAMP", NotNull: true },
    { Name: "Cost", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "Mem", Type: "TEXT" },
    { Name: "Name", Type: "VARCHAR(50)" },
    { Name: "IsCash", Type: "BOOLEAN", NotNull: true, Default: "false" },
    { Name: "BaseCode", Type: "SMALLINT" },
    { Name: "ID_Ref", Type: "INTEGER" },
    { Name: "ToExport", Type: "BOOLEAN", NotNull: true, Default: "false" },
  ],

  XInvoiceDatas: [
    { Name: "ID", Type: "INTEGER", PK: true },
    { Name: "ID_XInvoice", Type: "INTEGER", NotNull: true },
    { Name: "Pos", Type: "INTEGER", NotNull: true },
    { Name: "Name", Type: "TEXT", NotNull: true },
    { Name: "TypeEd", Type: "INTEGER", NotNull: true },
    { Name: "Amount", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "Price", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "Cost", Type: "DOUBLE PRECISION", NotNull: true },
    { Name: "ID_Car", Type: "INTEGER" },
    { Name: "Mem", Type: "TEXT" },
    { Name: "Type", Type: "INTEGER", NotNull: true },
    { Name: "IsFree", Type: "BOOLEAN", NotNull: true, Default: "false" },
    { Name: "Len", Type: "DOUBLE PRECISION" },
    { Name: "Hours", Type: "DOUBLE PRECISION" },
    { Name: "BaseCode", Type: "SMALLINT" },
    { Name: "ID_Ref", Type: "INTEGER" },
    { Name: "ToExport", Type: "BOOLEAN", NotNull: true, Default: "false" },
  ],
};

// =========================================
// Все индексы — теперь в одном месте!
// =========================================

// В файле schema.config.js — замени весь объект IndexesConfig на этот:
export const IndexesConfig = {
  Applications: [
    `CREATE INDEX IF NOT EXISTS idx_applications_date_reg          ON berg."Applications" ("DateReg")`,
    `CREATE INDEX IF NOT EXISTS idx_applications_datework_in       ON berg."Applications" ("DateWorkIn")`,
    `CREATE INDEX IF NOT EXISTS idx_applications_datework_out      ON berg."Applications" ("DateWorkOut")`,
    `CREATE INDEX IF NOT EXISTS idx_applications_customer          ON berg."Applications" ("ID_Customer")`,
    `CREATE INDEX IF NOT EXISTS idx_applications_customer_pay      ON berg."Applications" ("ID_CustomerPay")`,
    `CREATE INDEX IF NOT EXISTS idx_applications_customer_out      ON berg."Applications" ("ID_CustomerOut")`,
    `CREATE INDEX IF NOT EXISTS idx_applications_point_in          ON berg."Applications" ("ID_PointIn")`,
    `CREATE INDEX IF NOT EXISTS idx_applications_point_out         ON berg."Applications" ("ID_PointOut")`,
    `CREATE INDEX IF NOT EXISTS idx_applications_cargo             ON berg."Applications" ("ID_Cargo")`,
    `CREATE INDEX IF NOT EXISTS idx_applications_tariff            ON berg."Applications" ("ID_Tariff")`,
    `CREATE INDEX IF NOT EXISTS idx_applications_stage             ON berg."Applications" ("Stage")`,
    `CREATE INDEX IF NOT EXISTS idx_applications_nomer             ON berg."Applications" ("Nomer")`,
    `CREATE INDEX IF NOT EXISTS idx_applications_customer_date     ON berg."Applications" ("ID_Customer", "DateReg" DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_applications_pay_date          ON berg."Applications" ("ID_CustomerPay", "DateReg" DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_applications_period            ON berg."Applications" ("DateWorkIn", "DateWorkOut")`,
  ],

  XInvoices: [
    `CREATE INDEX IF NOT EXISTS idx_xinvoices_app       ON berg."XInvoices" ("ID_Application")`,
    `CREATE INDEX IF NOT EXISTS idx_xinvoices_date      ON berg."XInvoices" ("Date" DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_xinvoices_nomer     ON berg."XInvoices" ("Nomer")`,
    `CREATE INDEX IF NOT EXISTS idx_xinvoices_boss      ON berg."XInvoices" ("ID_Boss")`,
    `CREATE INDEX IF NOT EXISTS idx_xinvoices_fixed     ON berg."XInvoices" ("IsFixed")`,
  ],

  XInvoicePays: [
    `CREATE INDEX IF NOT EXISTS idx_xinvoicepays_invoice ON berg."XInvoicePays" ("ID_XInvoice")`,
    `CREATE INDEX IF NOT EXISTS idx_xinvoicepays_date     ON berg."XInvoicePays" ("Date" DESC)`,
  ],

  XInvoiceDatas: [
    `CREATE INDEX IF NOT EXISTS idx_xinvoicedatas_invoice ON berg."XInvoiceDatas" ("ID_XInvoice")`,
    `CREATE INDEX IF NOT EXISTS idx_xinvoicedatas_car     ON berg."XInvoiceDatas" ("ID_Car") WHERE "ID_Car" IS NOT NULL`,
  ],

  Customers: [
    `CREATE INDEX IF NOT EXISTS idx_customers_name   ON berg."Customers" ("NameShort")`,
    `CREATE INDEX IF NOT EXISTS idx_customers_inn    ON berg."Customers" ("INN") WHERE "INN" IS NOT NULL AND "INN" != ''`,
    `CREATE INDEX IF NOT EXISTS idx_customers_tariff ON berg."Customers" ("ID_Tariff")`,
  ],

  Tariffs: [
    `CREATE INDEX IF NOT EXISTS idx_tariffs_name ON berg."Tariffs" ("Name")`,
  ],

  Bosses: [
    `CREATE INDEX IF NOT EXISTS idx_bosses_name ON berg."Bosses" ("Name")`,
  ],

  Cargos: [
    `CREATE INDEX IF NOT EXISTS idx_cargos_name ON berg."Cargos" ("Name")`,
  ],

  xSaldo: [
    `CREATE INDEX IF NOT EXISTS idx_xsaldo_main ON berg."xSaldo" ("ID_CustomerPay", "ID_Boss")`,
    `CREATE INDEX IF NOT EXISTS idx_xsaldo_cash ON berg."xSaldo" ("IsCash")`,
  ],
};

// Порядок создания таблиц (важно для внешних ключей в будущем)
export const TablesOrder = [
  "Bosses",
  "Cargos",
  "Customers",
  "Tariffs",
  "xSaldo",
  "Applications",
  "XInvoices",
  "XInvoicePays",
  "XInvoiceDatas"
];